---
title: "transitreg: Transition Models Estimation"
author: "Nikolaus Umlauf, Reto Stauffer"
format: 
  html:
    html-math-method: mathjax
    toc: true
    number-sections: true
bibliography: transitreg.bib
vignette: >
  %\VignetteIndexEntry{transitreg}
  %\VignetteEngine{quarto::html}
  %\VignetteDepends{transitreg}
  %\VignetteKeywords{FIXME}
  %\VignettePackage{transitreg}
---

```{r stup}
#| echo: false
#| message: false
library("transitreg")
```

## Overview

```{r example_1}
set.seed(123)
n <- 1000
x <- runif(n, -3, 3)
y <- rpois(n, exp(2 + sin(x)))

## Fit transition count response model.
b <- transitreg(y ~ s(theta) + s(x))

## GAM summary.
summary(b)

## GAM coefficients
coef(b)

## Effect plots.
plot(b)

## Predictions and plotting.
nd <- data.frame(x = seq(-3, 3, length = 100))
fit <- cbind(
  "97.5%"  = predict(b, nd, type = "quantile", p = 1 - 0.05/2),
  "median" = predict(b, nd, type = "quantile", p = 0.5),
  "2.5%"   = predict(b, nd, type = "quantile", p = 0.05/2),
  "mode"   = predict(b, nd, type = "mode"),
  "mean"   = predict(b, nd, type = "mean")
)

## Plot data and fitted counts.
plot(y ~ x, pch = 16, col = rgb(0.1, 0.1, 0.1, alpha = 0.4))
matplot(nd$x, fit, type = "l", add = TRUE, lwd = 2,
       col = c(4, 4, 4, 2, 3), lty = c(2, 1, 2, 1, 1))
legend("topleft", legend = colnames(fit),
       col = c(4, 4, 4, 2, 3), lty = c(2, 1, 2, 1, 1))

```


```{r}
plot(b[1], tp = TRUE, cdf = FALSE)
```
